FROM golang:1.21-alpine

WORKDIR /app

COPY . .

RUN go mod download -x

RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -build="go build main.go" -command="./main"