// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/acerohernan/twirp-boilerplate/pkg/service"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	storage := createSessionStorage()
	authService := service.NewAuthService(storage)
	server := NewServer(authService)
	return server, nil
}

// wire.go:

func createSessionStorage() service.Storage {
	return service.NewLocalStorage()
}
